# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c43a5ce2d453d12cba510a4cfdcc3b9e911f3046cc2c51f6e3ab52c9f082eb5b43f930a17a8f0c810b0861cca78af20a183a5e0f885df289e04e632f1e8c18ee

test:
  secret_key_base: 61d2105129a0a8dd01026468b542815d59ef3f9f12ce69c25036ec2b252d7e114ad8c8eb6bde7a50fbd1fa956879571261323a8876f47f2a0116e7e2964868f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
